var personName = prompt("YourName")
var age = prompt("YourAge")
var a = prompt("EnglishMarks")
var b = prompt("urduMarks")
var c = prompt("PhysicsMarks")
var d = prompt("BiologyMarks")
var e = prompt("chemistryMarks")
console.log(a, "A value")
console.log(b, "B value")
console.log(c, "C value")
console.log(d, "D value")
console.log(e, "E value")
alert("total marks:447")
alert("Percentage 89.4%")
alert("Grade A+")
